// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Machine struct {
	RoomSlug      string `json:"room_slug"`
	ID            int32  `json:"id"`
	IsOperational bool   `json:"is_operational"`
	IsWasher      bool   `json:"is_washer"`
}

type Reservation struct {
	RoomSlug    string             `json:"room_slug"`
	MachineID   int32              `json:"machine_id"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
}
