// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearReservation = `-- name: ClearReservation :exec
DELETE FROM reservation
WHERE room_slug = $1
    AND machine_id = $2
`

type ClearReservationParams struct {
	RoomSlug  string `json:"room_slug"`
	MachineID int32  `json:"machine_id"`
}

func (q *Queries) ClearReservation(ctx context.Context, arg ClearReservationParams) error {
	_, err := q.db.Exec(ctx, clearReservation, arg.RoomSlug, arg.MachineID)
	return err
}

const getMachines = `-- name: GetMachines :many
SELECT m.id,
    m.is_operational,
    m.is_washer,
    r.end_at
FROM machine m
    LEFT JOIN reservation r ON r.room_slug = m.room_slug
    AND r.machine_id = m.id
WHERE m.room_slug = $1
ORDER BY m.id
`

type GetMachinesRow struct {
	ID            int32              `json:"id"`
	IsOperational bool               `json:"is_operational"`
	IsWasher      bool               `json:"is_washer"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) GetMachines(ctx context.Context, roomSlug string) ([]GetMachinesRow, error) {
	rows, err := q.db.Query(ctx, getMachines, roomSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMachinesRow
	for rows.Next() {
		var i GetMachinesRow
		if err := rows.Scan(
			&i.ID,
			&i.IsOperational,
			&i.IsWasher,
			&i.EndAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservationExists = `-- name: ReservationExists :one
SELECT EXISTS (
        SELECT 1
        FROM reservation
        WHERE room_slug = $1
            AND machine_id = $2
    ) AS exists
`

type ReservationExistsParams struct {
	RoomSlug  string `json:"room_slug"`
	MachineID int32  `json:"machine_id"`
}

func (q *Queries) ReservationExists(ctx context.Context, arg ReservationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, reservationExists, arg.RoomSlug, arg.MachineID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reserveMachine = `-- name: ReserveMachine :exec
INSERT INTO reservation (room_slug, machine_id, end_at, phone_number)
VALUES ($1, $2, $3, $4) ON CONFLICT (room_slug, machine_id) DO
UPDATE
SET end_at = EXCLUDED.end_at,
    phone_number = EXCLUDED.phone_number
`

type ReserveMachineParams struct {
	RoomSlug    string             `json:"room_slug"`
	MachineID   int32              `json:"machine_id"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
}

func (q *Queries) ReserveMachine(ctx context.Context, arg ReserveMachineParams) error {
	_, err := q.db.Exec(ctx, reserveMachine,
		arg.RoomSlug,
		arg.MachineID,
		arg.EndAt,
		arg.PhoneNumber,
	)
	return err
}

const setMachineAvailable = `-- name: SetMachineAvailable :exec
UPDATE machine
SET is_operational = TRUE
WHERE room_slug = $1
    AND id = $2
`

type SetMachineAvailableParams struct {
	RoomSlug string `json:"room_slug"`
	ID       int32  `json:"id"`
}

func (q *Queries) SetMachineAvailable(ctx context.Context, arg SetMachineAvailableParams) error {
	_, err := q.db.Exec(ctx, setMachineAvailable, arg.RoomSlug, arg.ID)
	return err
}

const setMachineOutOfOrder = `-- name: SetMachineOutOfOrder :exec
UPDATE machine
SET is_operational = FALSE
WHERE room_slug = $1
    AND id = $2
`

type SetMachineOutOfOrderParams struct {
	RoomSlug string `json:"room_slug"`
	ID       int32  `json:"id"`
}

func (q *Queries) SetMachineOutOfOrder(ctx context.Context, arg SetMachineOutOfOrderParams) error {
	_, err := q.db.Exec(ctx, setMachineOutOfOrder, arg.RoomSlug, arg.ID)
	return err
}
